### ISSUE TITLE
Error after importing from Aegis backup with Steam entries

### ISSUE THREAD

**Issue by jschenke488** [replydev/cotp#112]
As mentioned [here](https://github.com/beemdevelopment/Aegis/blob/master/docs/vault.md#entries), Aegis supports Steam entries. If a backup contains a Steam entry and it's imported into cotp, this error shows every time cotp is ran. I assume this same error would occur for Yandex entries, but I have not tested this.
![image](https://user-images.githubusercontent.com/44783760/190869224-31b3c615-8a58-41e8-830a-20b401e60e41.png)

Possible Solutions:
- skip steam and yandex entries and display a warning that these cannot be imported
- add support for steam and yandex

**Comment by replydev** [comment]
Hi and thank you for reporting, i will add support for steam and yandex.

**Comment by replydev** [comment]
3bd28da69bbc97e34dc97280c68110ce77f1f656

This is the first code for Steam support. Yandex will come soon. 
Can you let me know if this works for you?

**Comment by jschenke488** [comment]
It seems to work perfectly with Steam

**Comment by replydev** [comment]
Very well. The feature will come out in8 the next release. Thank you for reporting.
