### ISSUE TITLE
[Feature Request] In-UI HOTP counter incrementation

### ISSUE THREAD

**Issue by Alch-Emi** [replydev/cotp#13]
Howdy!

I just found this tool, and I think it's super handy!  I'm using it with an HOTP secret I need for a login I use regularly.  One problem I've encountered is that in order to increment the counter, I need to first run `cotp info -i <n>` to get the current counter value, followed by `cotp edit -i 1 --counter <x+1>` to increment it, then finally enter the UI with `cotp` to get the code - a process which involves entering my password three times, and a lot of commands, even if you have the index memorized.

I'd like to request a way to increment / decrement the counter from within the UI, perhaps incrementing it when the user presses Enter (+ copying the old code), and decrementing it with Shift+Enter, or whatever way you think best.  This would dramatically improve the workflow for using HOTP codes, and I think improve the software over all.

Thanks for the great software!

**Comment by replydev** [comment]
Hi, and thank you for your kindness. I will surely add your feature when i have some time. Thank you again.

**Comment by replydev** [comment]
Hi again. I implemented your feature, i think that is very useful so thanks for reporting. You have to wait for the next release or compile from sources if you are impatient ;).
To increment/decrement the HOTP counter just press '+' or '-'.

**Comment by Alch-Emi** [comment]
thank you so so much!!

On January 14, 2022 6:38:23 PM EST, Reply ***@***.***> wrote:
>Hi again. I implemented your feature, i think that is very useful so thanks for reporting. You have to wait for the next release or compile from sources if you are impatient ;).
>To increment/decrement the HOTP counter just press '+' or '-'.
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/replydev/cotp/issues/13#issuecomment-1013543688
>You are receiving this because you authored the thread.
>
>Message ID: ***@***.***>
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
