### ISSUE TITLE
Add protocol URL support to `cotp add`

### ISSUE THREAD

**Issue by brian6932** [replydev/cotp#157]
Would be better ux, and would allow it to work directly with decoded QR codes
```php
"otpauth://totp/$ISSUER:$LABEL?algorithm=$ALGORITHM&digits=$DIGITS&issuer=$ISSUER&period=$PERIOD&secret=$SECRET"
```

**Comment by replydev** [comment]
Yeah this could be useful. Thank you.

**Comment by replydev** [comment]
The only problem could be that the secret would be leaked in the shell history. @brian6932

**Comment by brian6932** [comment]
Yea, I guess you could always use a function to access the clipboard instead of pasting it directly, like in pwsh you can just do `(gcb)` or `(Get-Clipboard)`

**Comment by replydev** [comment]
Hi @brian6932, the upper PR implements an initial draft of the requested feature. Let me know your impressions. Thank you.

**Comment by brian6932** [comment]
![image](https://user-images.githubusercontent.com/18603393/207298481-2b16ab49-bade-4d6b-9186-94c6e7d373d5.png)

@replydev I couldn't figure out how to use this, in the PR, I tried `-u` and `--otpuri`
https://github.com/replydev/cotp/pull/159/files#diff-c3fd08257cd326dfa1c2a3c0a69e6b842f194950ac32e7b2c6e2750f52d1765fR40-R41

**Comment by replydev** [comment]
@brian6932 you have to call `cotp add --otpuri` and then it will ask for the OTP URI, so you can paste it.

**Comment by brian6932** [comment]
Ah ok that does work, imo this should be documented next to the entry if this is the chosen route for pasting, as it is a little ambiguous.

**Comment by replydev** [comment]
Yeah i've choosen this path becouse it's the same process as pasting the secret. I will merge that now. Thank you.

**Comment by brian6932** [comment]
Was this functionality removed?

**Comment by brian6932** [comment]
I guess I'll open a new issue

**Comment by brian6932** [comment]
>```php
>"otpauth://$TYPE/$ISSUER:$LABEL?algorithm=$ALGORITHM&digits=$DIGITS&issuer=$ISSUER&period=$PERIOD&secret=$SECRET"
>```
Minor issue with the current parser's that `$ISSUER:$LABEL` gets set as issuer instead of split into the right variables, if an issuer query param's detected, that should probably take precedence.
