### ISSUE TITLE
Question,Does it support piping to other app in.

### ISSUE THREAD

**Issue by LJWxyz** [replydev/cotp#185]
If possible,I wanted to pipe the output from this cli app to my own homemade app.
of example like a java calendar app used along with encryption then run this app and try get the output and verify as 2FA.
for example using,https://github.com/samdjstevens/java-totp
comparing to cotp values.

**Comment by replydev** [comment]
In the previous releases there was a **--json** argument which returned the OTP elements serialized in json format, but right row the only intended way to get the codes is via the TUI interface, so you will get some difficulties trying to call cotp via Java ProcessBuilder for example.

I advice you to choose a Java library to generate TOTP codes, or try to implement the functionality by yourself.
You can start from here https://github.com/beemdevelopment/Aegis, it's a very good project which contains all the code you need.

Thank you for your interest.
