### ISSUE TITLE
No issue: just some info

### ISSUE THREAD

**Issue by 5c0tt-b0t** [replydev/cotp#2]
Hi, first off, thank you! I love this!
Although Aegis is amazing, half the time, I need the code for the terminal and `cotp` does that perfectly, exporting from Aegis was made easy by `cotp` too.
In fact, it works so good that I went a step further completely deleted Aegis and built `cotp` on Termux (so I can still always access my codes away from my PC), now I am writing a small bash script for a Termux shortcut (a widget on my homescreen), when clicking it, **if** it detects a URL saved on my clipboard, it will try to find the coresponding entry (e.g https://github.com will return my github code, etc.), **else** prompts you to select one of your entries.
Good bye interpreted, memory-hogging Java and hello Rust! :)
So this is...
A: Thank you!
B: Reporting it works perfectly on Android for your ReadMe,
C: Whilst I was there, I noticed "Nix OS" wasnt listed, I can confirm it works on this distro too, another one for the ReadMe!

I'll close this now 🤣

**Comment by replydev** [comment]
Hi and **thank you** for your support! I will surely add your informations in the project's **README**. 
If you want to publish your script i will be happy to insert your repository link in my **README**. **Thanks again!**

**Comment by replydev** [comment]
I was trying to compile cotp in termux using the `rust` package, installed with `pkg install rust`. 
I get an error during libsodium compilation. Have i to do some other steps to get a functional rust enviroment?
[output.txt](https://github.com/replydev/cotp/files/6006528/output.txt)

**Comment by 5c0tt-b0t** [comment]
@replydev you can install it with `apt install libsodium` then it will build.
Honestly, once thats done, you should be good to go! 👍 

If you have **any** problems, just ask me, I'd be happy to help!
As for the script, I wont bother making it a repo, but I'd gladly share it with you and your users, its nice to not have to open a terminal first, either hit the shortcut on the home screen or use the "share" function instead!

**Comment by replydev** [comment]
It compiles with no issues after installing all the packages you wrote, thanks for help.
