### ISSUE TITLE
Export to widely know format

### ISSUE THREAD

**Issue by GRbit** [replydev/cotp#270]
It's super nice that I can import my keys from a various of formats, but sometimes I also want to sync my keys to others apps that I use. For example, there is Aegis on my mobile device and after I tried all the options that it suggests (more than 10 formats) and none of them fit.

It would be nice to have an option to export data to widely know format.

I would appreciate any recommendation in utils to convert cotp export to any of formats which is know by Aegis.

List of formats available for Aegis:
2FAS Authenticator
Aegis
andOTP
Authenticator Plus
Authy
Battle.net Authenticator
Bitwarden
Duo
FreeOTP
FreeOTP+
Google Authenticator
Microsoft Authenticator
Plain Text (have no idea on the format, though)
Steam
TOTP Authenticator
WinAuth

**Comment by replydev** [comment]
Thank you, that could be good to make cotp even more usable.

I would implement this feature, in the mean time you can try to:
- Export the cotp database using **cotp export**.
- Extract the JSON array containing the OTP codes into a separate file.
- Import this file as an andOTP file (yes, cotp format is roughtly the same as andOTP)

Let me know if that works, thank you.

**Comment by GRbit** [comment]
@replydev thank you for those details!
andOTP import worked flawlessly after extracting keys array.

Just a small snipped for anyone who will read this in the future:
`cotp export && cat exported.cotp | jq '.elements' > andOTP.json`
P.S.: Don't forget to delete those file, since they aren't encrypted

**Comment by replydev** [comment]
Very nice, thank you!
