### ISSUE TITLE
segfault in cipher

### ISSUE THREAD

**Issue by bAndie91** [replydev/cotp#31]
hi, i got this segfault, see details:

- cotp commit 49d2c1f
- cargo 1.58.0 (f01b232bc 2022-01-19)
- cargo build target: release
- `~/.cotp/db.cotp` does not exist
- failing command: `cotp add -i xyz -l xyz@xyz -a SHA1 -d 6`

```
(gdb) bt
#0  0x8000a4ca in chacha20poly1305::cipher::Cipher$LT$C$GT$::new::hed69a7d757b7398b ()
#1  0x800327f7 in cotp::database_management::overwrite_database_json::h53b38a1489223167 ()
#2  0x8003b4e8 in cotp::main::h633cef697bb2ae07 ()
#3  0x8000b6ae in std::sys_common::backtrace::__rust_begin_short_backtrace::hcb8c7447e08876a5 ()
#4  0x8003e256 in main ()
```

**Comment by bAndie91** [comment]
commit 0a0478e (tag 0.1.9) works well in this regard.

**Comment by replydev** [comment]
Thank you for reporting, i will inspect the error and fix.

**Comment by bAndie91** [comment]
i've done it already, it's fresh:

```
active toolchain
----------------

stable-i686-unknown-linux-gnu (default)
rustc 1.58.1 (db9d1b20b 2022-01-20)
```

yes it asked the secret and then the db password.

**Comment by replydev** [comment]
So it works now?

**Comment by bAndie91** [comment]
no, i just confirmed that rust is recent which i compiled with and it asked the inputs, then crashed.
have not tested since my opening attempt.

**Comment by replydev** [comment]
Closed for lack of replicability. Feel free to reopen the issue if you still have the problem.
Regards
