### ISSUE TITLE
[Feature request] Is it possible to add a Page Up/Down page navigation feature for the UI

### ISSUE THREAD

**Issue by PM2p5** [replydev/cotp#327]
Hi, @replydev!

Many users may have no more than two pages of codes, if it could use the Page Up/Page Down key to navigate to the previous/next page, it could be much easier than using current arrow keys or the Ctrl+F combination.

Thanks in advance!

### Portable Mode

Cotp supports both Portable mode and XDG_DATA_HOME:

    If COTP_DB_PATH is set, use that as the full path.
    If $(pwd)/db.cotp exists, use that path for portability mode.
    If ~/.cotp exists, use that prefix for backwards compatibility but warn the default location has changed.
    Check if XDG_DATA_HOME is set, if so use it as prefix with $XDG_DATA_HOME/cotp.
    If not, set the hard coded prefix to .local/share/cotp

### In-UI HOTP counter incrementation/decrementation

To increment/decrement the HOTP counter just press '+' or '-'.

### Search codes with Ctrl + F

Use Ctrl + F key combination will allow you to to filter issuers/labels and etc.

### Page Up/Page Down navigation

Use Page Up/Page Down key to navigate to the previous/next page.

## The following texts are for the in App help menu

Press:
Arrow Up/Arrow Down -> Previous/next element
Page Up/Page Down -> Previous/next page
Enter -> Copy the OTP Code to the clipboard
k -> Show QR-Code of the selected element
CTRL-F -> Search codes
CTRL-W -> Clear the search query
\+ -> Increment the HOTP counter
d -> Delete selected code
Esc/q -> Exit

**Comment by replydev** [comment]
Hey @PM2p5 thanks a lot for the new features introduction. I think add pages better than the current solution. I will implement that.
