### ISSUE TITLE
convert export.cotp

### ISSUE THREAD

**Issue by d4op** [replydev/cotp#380]
How to convert he export from cotp ?
i mean "cotp export"

i need the files back converted for other tools like freeotp+

**Comment by replydev** [comment]
Hello @d4op, currently exporting to FreeOTP+ format is not yet supported, but could easily being implemented. Thanks for reporting.

**Comment by replydev** [comment]
Hello @d4op the exporter into FreeOTP+ format has been implemented. Please use `-f` to export to that format.

**Comment by d4op** [comment]
how to update my old installation ?
just redo setup like this ?
git clone https://github.com/replydev/cotp.git
cargo install --path cotp/

or will this kill my current database ?

**Comment by d4op** [comment]
maybe you can add https://getaegis.app/ support too for export

**Comment by d4op** [comment]
how does export work right ?

like this ?
cotp export --aegis ?
cotp export -f ?

i mean is the export working for all supported input switches ?

**Comment by d4op** [comment]
i want all secrets back from cotp exported to a specific format like free-otp++ with -f 
or example to aegis back

**Comment by d4op** [comment]
cant update the cotp version.. some compile error now no idea why. didnt change anything to the host.
can you please tell me how to convert the normal export .cotp to like aegis or free-otp++
