### ISSUE TITLE
How can I use Cotp with Microsoft Teams?

### ISSUE THREAD

**Issue by fadedbee** [replydev/cotp#392]
Microsoft Teams gives me a (non-URI) account name "Example Inc:fadedbee@example.com" and a secret key "8khfaew89hef9".  (Not real values, just examples of the format.)

How do I add these to Cotp?
```
$ cotp add
error: the following required arguments were not provided:
  --otpuri
  --label <LABEL>

Usage: cotp add --otpuri --label <LABEL>
```

**Comment by replydev** [comment]
Hello @fadedbee, you could use the standard add command flags.

`cotp add -i YourIssuer -l YourLabel`

Then, a prompt will require the secret.

The label flag is the only required.

Please use also `cotp add --help` to check additional flags that may be useful to you.
