### ISSUE TITLE
thread 'main' panicked at 'called `Result::unwrap()`

### ISSUE THREAD

**Issue by burp** [replydev/cotp#4]
I added a new OTP code, but now cotp crashes when trying to unlock. Did I insert some invalid characters by accident?

cotp v0.1.7
written by @replydev

Password:
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: InvalidSecret(DecodeError { position: 6, kind: Symbol })', src/otp/otp_helper.rs:67:90
stack backtrace:
   0:     0x5557804e2730 - std::backtrace_rs::backtrace::libunwind::trace::h38f496e2f60ff056
                               at /build/rust/src/rustc-1.51.0-src/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1:     0x5557804e2730 - std::backtrace_rs::backtrace::trace_unsynchronized::h56106da60d2adf4e
                               at /build/rust/src/rustc-1.51.0-src/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x5557804e2730 - std::sys_common::backtrace::_print_fmt::he96612ccef88d499
                               at /build/rust/src/rustc-1.51.0-src/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x5557804e2730 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h7bc9abcb54e035e8
                               at /build/rust/src/rustc-1.51.0-src/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x5557804ff4ac - core::fmt::write::hc902605fce7cd9d0
                               at /build/rust/src/rustc-1.51.0-src/library/core/src/fmt/mod.rs:1096:17
   5:     0x5557804df845 - std::io::Write::write_fmt::hc1b61b7b2ff05b80
                               at /build/rust/src/rustc-1.51.0-src/library/std/src/io/mod.rs:1568:15
   6:     0x5557804e4855 - std::sys_common::backtrace::_print::hbfdf09e2f4163e71
                               at /build/rust/src/rustc-1.51.0-src/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x5557804e4855 - std::sys_common::backtrace::print::h0f74697e38abc595
                               at /build/rust/src/rustc-1.51.0-src/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x5557804e4855 - std::panicking::default_hook::{{closure}}::hddc95caf81a22541
                               at /build/rust/src/rustc-1.51.0-src/library/std/src/panicking.rs:208:50
   9:     0x5557804e43b3 - std::panicking::default_hook::h3eba1f2638a2c835
                               at /build/rust/src/rustc-1.51.0-src/library/std/src/panicking.rs:225:9
  10:     0x5557804e4ff1 - std::panicking::rust_panic_with_hook::h8f88f1391abedf2a
                               at /build/rust/src/rustc-1.51.0-src/library/std/src/panicking.rs:591:17
  11:     0x5557804e4b37 - std::panicking::begin_panic_handler::{{closure}}::hf473b53e26f56dd7
                               at /build/rust/src/rustc-1.51.0-src/library/std/src/panicking.rs:497:13
  12:     0x5557804e2bcc - std::sys_common::backtrace::__rust_end_short_backtrace::h6fde4603ccb02286
                               at /build/rust/src/rustc-1.51.0-src/library/std/src/sys_common/backtrace.rs:141:18
  13:     0x5557804e4a99 - rust_begin_unwind
                               at /build/rust/src/rustc-1.51.0-src/library/std/src/panicking.rs:493:5
  14:     0x5557804fde41 - core::panicking::panic_fmt::hac8c69602870cdf7
                               at /build/rust/src/rustc-1.51.0-src/library/core/src/panicking.rs:92:14
  15:     0x5557804fdc63 - core::option::expect_none_failed::h7dfb96068fc9393b
                               at /build/rust/src/rustc-1.51.0-src/library/core/src/option.rs:1300:5
  16:     0x5557804760f0 - cotp::otp::otp_helper::get_good_otp_code::hc0c2526e9ba65e40
  17:     0x5557804757a6 - cotp::otp::otp_helper::show_codes::h48fb5873267a30a8
  18:     0x555780477d0f - cotp::main::h3f3a62180fef9322
  19:     0x5557804786f3 - std::sys_common::backtrace::__rust_begin_short_backtrace::ha6798c2b8a70492a
  20:     0x55578046aa89 - std::rt::lang_start::{{closure}}::h06055368eb7f2e5f
  21:     0x5557804e5417 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h6646ba386ff34dbe
                               at /build/rust/src/rustc-1.51.0-src/library/core/src/ops/function.rs:259:13
  22:     0x5557804e5417 - std::panicking::try::do_call::h47e376e14a330979
                               at /build/rust/src/rustc-1.51.0-src/library/std/src/panicking.rs:379:40
  23:     0x5557804e5417 - std::panicking::try::hb7ef6d6b3d4db346
                               at /build/rust/src/rustc-1.51.0-src/library/std/src/panicking.rs:343:19
  24:     0x5557804e5417 - std::panic::catch_unwind::h534d7ac891813066
                               at /build/rust/src/rustc-1.51.0-src/library/std/src/panic.rs:431:14
  25:     0x5557804e5417 - std::rt::lang_start_internal::h8191eeb0dbee8736
                               at /build/rust/src/rustc-1.51.0-src/library/std/src/rt.rs:51:25
  26:     0x555780477e82 - main
  27:     0x7fbb4bec1b25 - __libc_start_main
  28:     0x55578045c17e - _start
  29:                0x0 - <unknown>

**Comment by replydev** [comment]
Hi, probably you inserted a bad otp code and the program cannot handle the exception correctly.

**Comment by replydev** [comment]
Hi, have you faced this bug other times? Can you give me an example OTP Secret to be able to replicate the problem?

**Comment by burp** [comment]
As you suggested, it's due to a bad otp code:

Step 1: Create a new database
Step 2: cotp -a foo foo TOTP 6
Step 3: Choose foobar123 as secret

**Comment by replydev** [comment]
Hi, with the advent of the new releases i implemented a secret validation. The problem should be fixed right now. Please reopen the issue if you get the issue again.
