### ISSUE TITLE
Feature Request: A way to share HOTP/TOTP URI outside of QR encoding

### ISSUE THREAD

**Issue by brian6932** [replydev/cotp#413]
Sometimes you may want to just share the URI, and not export all TOTP/HOTP URIs, it'd be nice when you press `k` to view the QR code, to also get a non-QR encoded version of URI. This could be it's own bind as well, something like `Enter` that copies the code to clipboard can work as well (maybe `Shift+Enter`). Saves the hassle of having to screenshot the QR code and use something like qrrs on it.

**Comment by replydev** [comment]
Hello, I do now know if it is good from a security prospective to show the full OTP URI in clear text, but of course we could copy the URI if we are in the QR code screen. What do you think about it?

**Comment by brian6932** [comment]
Yea that's fine, that's the same way that Aegis does it (although with a button).
