### ISSUE TITLE
No way to import OTP URIs as strings (from stdin or arguments) without files

### ISSUE THREAD

**Issue by brian6932** [replydev/cotp#423]
Mentioned in https://github.com/replydev/cotp/issues/157#issuecomment-2062952310.
Previously `cotp add --otpuri` would allow this.

**Comment by replydev** [comment]
Thanks for reporting. I will try to replicate and release a fix.
I do not receive notifications for new messages in closed issues. Please always open a new issue.

**Comment by replydev** [comment]
So, in #425 the feature removal from a single OTP Uri has been reverted. You can now add the OTP Uri as before.

Said that, the importing error that you faced has been made a bit more clear. The error was the format that you were trying to import. All the import files must be JSON files with a string predefined schema.
Please read: https://github.com/replydev/cotp?tab=readme-ov-file#migration-from-other-apps for futher information.

**Comment by brian6932** [comment]
It should just work with (cr)lf and/or whitespace in general separated list as well imo (This is how https://github.com/bingzheung/authenticator exports & imports, and also most natural for a user, so it makes sense imo).

**Comment by brian6932** [comment]
Basically, I would like to do things like
```
qrrs -r qrcode.png | cotp add -u
```
which would decode a QR code, and then pipes the text into `add`. Currently I'd have to do something like
```
qrrs -r qrcode.png | scb
cotp add -u
Password:

Insert the otp uri: <paste>
```
