### ISSUE TITLE
How to setup github's 2FA with cotp?

### ISSUE THREAD

**Issue by RokerHRO** [replydev/cotp#440]
Github enforces 2FA now, so I'd like to use cotp for that.

Github shows a dialog: "Setup authenticator app" and there is a QR code. -> unusable for command line tool.
The dialog also a "Setup key", when I click on it, a 16-char code is shown, but no URL.

But cotp wants an URL -> what shall I enter here?

I think github's 2FA enforcement would give you a lot of  new users, but at the moment I am completely lost and a README-gitgub.md would be nice. :-)

I scanned the QR code from the Github dialog. It contains an URI like this:
`otpauth://totp/GitHub:RokerHRO?secret=★★★★★★★★&issuer=GitHub` but that is not accepted by `cotp add -u`:

```
error: unexpected argument 'otpauth://totp/GitHub:RokerHRO?secret=★★★★★★★★&issuer=GitHub'
```

:-(

**Comment by replydev** [comment]
Hello @RokerHRO. In this case you would just need to execute `cotp add -l Github`.
Without the `-u` flag, it will prompt for the BASE32 secret that GitHub shown to you. Copy and paste it and you are good to go.

**Comment by RokerHRO** [comment]
> Hello @RokerHRO. In this case you would just need to execute `cotp add -l Github`. Without the `-u` flag, it will prompt for the BASE32 secret that GitHub shown to you. Copy and paste it and you are good to go.

Nice. I didn't know what this "label" is good for.

I think this could be mentioned as example in the README.md for any impatient user. :-)

**Comment by replydev** [comment]
Yeah I totally agree. A new revision is coming :)

**Comment by RokerHRO** [comment]
A question to the "label" parameter: Is it an arbitrary name, just for the user? Or are other config parameters associated with this label, e.g. if `label == "Github" then algorithm=SHA1, digits=6, period=30 etc. ?

**Comment by replydev** [comment]
Hello @RokerHRO, the label is just an arbitrary name that you give to the OTP Code.

Please check also: https://github.com/google/google-authenticator/wiki/Key-Uri-Format#label

**Comment by RokerHRO** [comment]
Okay, so where do the other configuration values (algorithm, digits, period) come from?

I'd still like to see an example how to use `cotp` with Github's 2FA in your `README.md` :-)
