### ISSUE TITLE
Make secret validation case-insensitive ?

### ISSUE THREAD

**Issue by hazayan** [replydev/cotp#449]
Hi

When feeding lower-case secrets to the command line it rejects them with a message that is not informative as to the reason. It would help to either make secret input case-insensitive or add a meaningful error message to help the user.

**Comment by replydev** [comment]
Hello @hazayan thanks for reporting.

I absolutely agree and will release a fix soon.

**Comment by replydev** [comment]
Resolved in #453

**Comment by hazayan** [comment]
Awesome @replydev  1 Thank you so much ! Keep up the great work !
