### ISSUE TITLE
index mismatch

### ISSUE THREAD

**Issue by presianbg** [replydev/cotp#457]
Hi,

Just noticed that the main interactive screen show  index starting at `1`:
![image](https://github.com/user-attachments/assets/298d3400-e1e2-47ad-b936-cc4c6e83d144)

, but the `list` command starts from `0`:

![image](https://github.com/user-attachments/assets/3526d114-23f4-4765-b4e4-b9dee3a50a3b)

this brings some confusion when using the `edit` functionality, because it uses the same logic as the interactive interface, but the `list` is more convenient for the job.

Cheers,
PY

**Comment by replydev** [comment]
Hello @presianbg you are totally right and I am gonna fix this.
