### ISSUE TITLE
[Feature request] Deleting entries from the database

### ISSUE THREAD

**Issue by qweri0p** [replydev/cotp#460]
**Is your feature request related to a problem? Please describe.**
I've deleted my account for a service which uses TOTP authentication. I added it to cotp, and now I wish to remove it.

**Describe the solution you'd like**
A command like `cotp delete`. With selection options just like `cotp edit`.
Example: `cotp delete -s Github`

**Additional context**
A confirmation should be included.

**Comment by replydev** [comment]
Hello @qweri0p, this is a good idea and I will implement it in the next days.

In the mean time, you can delete an OTP code in the interactive dashboard, by selecting your desired one and pressing **d**.

Once you quit the dashboard you will be asked to confirm.
