### ISSUE TITLE
Document the need for libxcb development libs and headers in the README

### ISSUE THREAD

**Issue by wizardlink** [replydev/cotp#48]
Hello! Opening this issue to raise awareness for this necessity since I went to install the package through `cargo` and it gave me the error:
```
  = note: /usr/bin/ld: cannot find -lxcb-render
          /usr/bin/ld: cannot find -lxcb-shape
          /usr/bin/ld: cannot find -lxcb-xfixes
```

To resolve that I installed the `libxcb-devel` (in Fedora 35) package, which wasn't specified in the README, I think it's important to have it there highlighted as a dependency.

**Comment by replydev** [comment]
Hi and thank you for reporting. I have added a section referring to the libxcb dependency.
Regards.
