### ISSUE TITLE
Read master password from an env var

### ISSUE THREAD

**Issue by dodalovicgran** [replydev/cotp#487]
Hi, 
I was thinking - I'm lazy to type the password each time I run the app. Maybe the app could read some env var, if there's one?

Kind regards
Dusan

**Comment by replydev** [comment]
Hello, this program supports the `--password-stdin` argument.

Example usage:
`echo "mySecretPassword" | cotp --password-stdin`

Of course you can use any password manager to get your passcode, so you could create an alias to your`.zshrc` (or whetever you use) like this example:

`alias cotp="pass personal/cotp | cotp --password-stdin"`

**Comment by replydev** [comment]
Closing this issue. Feel free to reopen if the solution does not work.

**Comment by dodalovicgran** [comment]
Thank you, it works with the alias, I can live with it :)
