### ISSUE TITLE
Add info about `xclip` as a depenency in linux

### ISSUE THREAD

**Issue by owzim** [replydev/cotp#501]
On a new system I had not installed `xclip` and was wondering, why `cotp` did not copy the codes to the clipboard. No error messages. Installing `xclip` fixed it, but this info is nowhere to be found.

**Comment by replydev** [comment]
Hello @owzim and thanks for your report!

Could you please state which distribution and version has this issue?

**Comment by owzim** [comment]
@replydev `Linux Mint 22.0`, based on `Ubuntu 24.04`
