### ISSUE TITLE
Can you make the json import work with another Authy exporter?

### ISSUE THREAD

**Issue by brian6932** [replydev/cotp#54]
https://gist.github.com/gboudreau/94bb0c11a6209c82418d01a59d958c93 This is a root-less way to acquire Authy tokens, and doesn't require any conversion, can this method be parsed as well? Currently when attempting to import, I receive this error:
![image_201](https://user-images.githubusercontent.com/18603393/162631645-966f2fd6-5b45-4bb5-aff4-7cea251a54f3.png)

**Comment by brian6932** [comment]
https://z.zz.fo/CsFvQ.json Example exported json

**Comment by replydev** [comment]
Hello, exporting the Authy database from the desktop app seems very interesting!
This commit https://github.com/replydev/cotp/commit/06acaef796206b2d57b5b30b09cf501ad7c77d14 should add the required import functionality. The import flag is `-u` or `--authy-exported`.
Could you test and let me know?
Regards

**Comment by brian6932** [comment]
works 👍
